### ISSUE TITLE
require("electron-windows") 失败

### ISSUE THREAD

**Issue by 425824365** [xudafeng/electron-windows#6]
基于vue-cli-plugin-electron-builder，本地开发时引用electron-windows报错
`
Module parse failed: Unexpected token (7:10)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| class WindowsManager {
>   windows = {};
|
|   create(options) {

 @ ./node_modules/_electron-windows@0.2.1@electron-windows/index.js 3:17-50
`

**Comment by 425824365** [comment]
目前是将 electron-windows拉下来然后将 windows = {}; 放到WindowsManager类中constructor函数，但不知道会不会有问题

**Comment by xudafeng** [comment]
@425824365 在主进程中引入
